name: Validate and Deploy HTML on gh-pages

on:
  push:
    branches:
      - main  # El flujo de trabajo se ejecutará cuando haya un push a la rama 'main'

jobs:
  validate_and_deploy:
    runs-on: ubuntu-latest  # Usamos Ubuntu para ejecutar los jobs

    steps:
      # 1. Checkout de la rama gh-pages (trabajamos directamente en la rama gh-pages)
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages  # Aquí estamos haciendo checkout de la rama 'gh-pages'

      # 2. Validar el HTML en la rama gh-pages
      - name: Validate HTML on gh-pages
        run: |
          if [ ! -f index.html ]; then
            echo "index.html no encontrado!"
            exit 1
          else
            echo "index.html encontrado!"
          fi

          # Validar que el formulario esté presente
          if ! grep -q '<form id="contact-form"' index.html; then
            echo "El formulario no está presente!"
            exit 1
          fi

          # Validar que el campo de nombre esté presente
          if ! grep -q 'id="name"' index.html; then
            echo "El campo de nombre no está presente!"
            exit 1
          fi

          echo "Validaciones de HTML completadas con éxito!"

      # 3. Crear el archivo optimizado en la rama gh-pages
      - name: Create optimized HTML in gh-pages
        run: |
          cp index.html optimized_index.html  # Simulación de optimización
          echo "Archivo optimizado creado como optimized_index.html"

      # 4. Configuración para hacer commit y push a gh-pages
      - name: Commit and push changes to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add -A
          git commit -m "Optimized HTML files deployed to gh-pages"
          git push origin gh-pages  # Push de los archivos optimizados a la rama gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para hacer el push a gh-pages
